version: "3"

networks:
  service_network:
    name: service_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
        
volumes:
  node_library:
  vendor_library:

services:
  app:
    tty: true
    restart: always
    build: ./xdebug
    volumes:
      - ./src:/opt/html
      - ./logs/nginx:/var/log/nginx
      - ./logs/php:/var/log/php8
      - node_library:/opt/html/node_modules
      - vendor_library:/opt/html/vendor
    ports: 
      - "8080:80"
      - "9003:9003"
    networks:
      service_network:
        ipv4_address: 172.20.0.2

  db:
    tty: true
    restart: always
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysqldump:/opt/mysqldump
      - ./logs/mysql:/var/log/mysql
    networks:
      service_network:
        ipv4_address: 172.20.0.3
